server:
  port: 8083

spring:
  application:
    name: notificacao-service
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_notificacao?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: 8adjt.grupo4@gmail.com
    password: passwordGRUPO4
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
  exchange:
    consultas: consultas.exchange
  queue:
    notificacao: notificacao.queue
  routing:
    key:
      notificacao: consulta.notificacao

logging:
  level:
    com.hospital: DEBUG
    org.springframework.mail: DEBUG