version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hospital-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_agendamento
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hospital-network

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: hospital-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - hospital-network

volumes:
  mysql_data:
  rabbitmq_data:

networks:
  hospital-network:
    driver: bridge